export class Entidadbeneficiaria {
  id?:number;
  idEntidad?:number;
  nombre?:String;
  representante?:String;
  emailEntidad?:String;
  emailRepresentante?:String;
  telefonoEntidad?:String;
  celularRepresentante?:String;
  fechaCreacion?:Date;
  idCoordinador?:number;
  nombreCoordinador?:string;
  ciudad?:string;
  direccion?:string;
  nombreAdministrador?:string;
  cedulaAdministrador?:string;
  correoAdministrador?:string;
  descripcionEmpresa?:string;
}
